Add login
automat-ed/portal pull request #23
Opened 2021-03-14 17:00 UTC by alexchelba

Closes #9 #10 
Login system uses bcrypt encryption for the password and stores a cookie of the user logged in.

2021-03-17 02:38 UTC, Siliconlad requested changes
Sorry for all the comments! The implementation is really good overall, it's just a lot of very small things. Can you also delete  models/notifications.js`?

2021-03-17 02:38 UTC, Siliconlad commented on models/users.js
> +			if (err) return next(err)
```suggestion
			if (err) return next(err);
```

2021-03-17 02:38 UTC, Siliconlad commented on models/users.js
> +	if (user.isModified('password')) {//checking if password field is available and modified
Why do we generate a new hash when the password has been modified?

```suggestion
	if (user.isModified('password')) { //checking if password field is available and modified
```

2021-03-17 02:38 UTC, Siliconlad commented on models/users.js
> +//for comparing the users entered password with database duing login
```suggestion

// For comparing the users entered password with database duing login 
```

2021-03-17 02:38 UTC, Siliconlad commented on models/users.js
> +//for generating token when loggedin
```suggestion

// For generating token when logged in
```

2021-03-17 02:38 UTC, Siliconlad commented on models/users.js
> +//validating token for auth routes middleware
```suggestion

// Validating token for auth routes middleware
```

2021-03-17 02:38 UTC, Siliconlad commented on models/users.js
> +		callBack(null, user)
```suggestion
		if (err) return callBack(err);
		callBack(null, user);
```

2021-03-17 02:38 UTC, Siliconlad commented on models/users.js
> +	jwt.verify(token, process.env.ACCESS_TOKEN_SECRET, function (err, decode) {//this decode must give user_id if token is valid .ie decode=user_id
```suggestion
	jwt.verify(token, process.env.ACCESS_TOKEN_SECRET, function (err, decode) { // This decode must give user_id if token is valid. ie decode=user_id
```

2021-03-17 02:38 UTC, Siliconlad commented on models/users.js
> +var us = new mongoose.Schema({
Not a big deal, but I'm not a huge fan of calling the schema `us`. Something like `User` would be better I think.

2021-03-17 02:38 UTC, Siliconlad commented on middleware/auth.js
> +module.exports = { auth }
```suggestion
module.exports = { auth };

```

2021-03-17 02:38 UTC, Siliconlad commented on helpers/validator.js
> +module.exports.loginValidator = loginValidator;
```suggestion
module.exports.loginValidator = loginValidator;

```

2021-03-17 02:38 UTC, Siliconlad commented on app.js
> +    res.sendFile(path.join(__dirname,'./public/login.html'))
```suggestion
    res.sendFile(path.join(__dirname, 'public', 'login.html'));
```

2021-03-17 02:38 UTC, Siliconlad commented on app.js
> +app.get('/auth',auth, getUserDetails);
```suggestion
app.get('/auth', auth, getUserDetails);
```

2021-03-17 02:38 UTC, Siliconlad commented on controller/AuthController.js
> +//const db = require('../models/db');
```suggestion
```

2021-03-17 02:38 UTC, Siliconlad commented on controller/AuthController.js
> +const Notif = require("../models/notifications");
```suggestion
```

2021-03-17 02:38 UTC, Siliconlad commented on controller/AuthController.js
> +	});
Indentation seems weird here.

2021-03-17 02:38 UTC, Siliconlad commented on controller/AuthController.js
> +			return res.status(404).json({ success: false, message: 'Username not found!' });
I'm not sure if 404 is the right status code. Something like 401 may be more appropriate. See [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status) for the list of HTTP status codes.

Also, for security reasons, we shouldn't tell the front-end whether the username was correct or not. I would change it to "invalid credentials" or something like that.

2021-03-17 02:38 UTC, Siliconlad commented on controller/AuthController.js
> +					return res.status(400).json({ success: false, message: 'Wrong Password!' });
Same here, we shouldn't tell them that the password is incorrect, then the attacker knows that the username is correct. We should just say "invalid credentials" or something like that.

Also, 401 would probably be more appropriate than 400.

2021-03-17 02:38 UTC, Siliconlad commented on controller/AuthController.js
> +				//isMatch is eaither true or false
```suggestion
```

2021-03-17 02:38 UTC, Siliconlad commented on controller/AuthController.js
> +							return res.status(400).send({ err });
Would this not be a server error and so a `5xx` code be more appropriate? Also do we want to send the entire error to the frontend?

2021-03-17 02:38 UTC, Siliconlad commented on controller/AuthController.js
> +							//saving token to cookie
```suggestion
							// Saving token to cookie
```

2021-03-17 02:38 UTC, Siliconlad commented on controller/AuthController.js
> +							res.cookie('authToken', user.token, {maxAge: 28800 * 1000, httpOnly: true}); // available 8h
```suggestion
							res.cookie('authToken', user.token, {maxAge: 28800 * 1000, httpOnly: true}); // Available 8h
```

2021-03-17 02:38 UTC, Siliconlad commented on controller/AuthController.js
> +//get authenticated user details
```suggestion

// Get authenticated user details
```

2021-03-17 02:38 UTC, Siliconlad commented on controller/AuthController.js
> +exports.getUserDetails= (req, res) => {
```suggestion
exports.getUserDetails = (req, res) => {
```

2021-03-17 02:38 UTC, Siliconlad commented on controller/AuthController.js
> +}
```suggestion
```

2021-03-17 02:38 UTC, Siliconlad commented on controller/AuthController.js
> +}
```suggestion
```

2021-03-17 02:38 UTC, Siliconlad commented on app.js
> +app.get('/auth',auth, getUserDetails);
What is the point of this route?

2021-03-17 02:38 UTC, Siliconlad commented on controller/AuthController.js
> +}
```suggestion
```

2021-03-17 02:38 UTC, Siliconlad commented on app.js
> +app.get('/index', auth, getAlli);
Is there a reason why we need both `/` and `/index`? Can't we combine the two?

2021-03-17 09:14 UTC, alexchelba commented on app.js
> +app.get('/index', auth, getAlli);
mmm, / takes you to either /login or /index, depends if yo are logged in. Think they can be combined, tho' I also think functionality is better defined as it is now. Do you think it's worth changing?

2021-03-17 09:28 UTC, alexchelba commented on app.js
> +app.get('/auth',auth, getUserDetails);
Not a key one, if u write /auth you can see details of the logged in user. Wee help for hackers.

2021-03-17 12:14 UTC, Siliconlad commented on app.js
> +app.get('/auth',auth, getUserDetails);
I suppose this could be useful for the user to be able to see their own details if we create some sort of profile page.

2021-03-17 12:16 UTC, Siliconlad commented on app.js
> +app.get('/index', auth, getAlli);
The way I think of it is that `/` is the index page, but if you are not loggedin then it redirects to `/login`. Once you login you are then allow to go to the index page at `/`.  I this is a simpler set up no?

2021-03-26 12:38 UTC, alkg approved these changes

2021-03-28 17:19 UTC, alexchelba reviewed
Complete integration of login system

2021-03-28 19:09 UTC, Siliconlad commented
Superseded by #27

2021-03-28 19:09 UTC, closed without merging